# Generated by Django 3.2.4 on 2021-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSapp', '0002_contact_contact2'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageWale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='profiles')),
            ],
        ),
    ]
